# Generated by Django 5.0.1 on 2024-03-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aktor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imie", models.CharField(max_length=32)),
                ("nazwisko", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="ExtraInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "czas_trwania",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "gatunek",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (4, "Dramat"),
                            (0, "Inne"),
                            (2, "Komedia"),
                            (1, "Horror"),
                            (3, "Sci-fi"),
                        ],
                        null=True,
                    ),
                ),
                ("rezyser", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ocena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recenzja", models.TextField(blank=True, default="")),
                ("gwiazdki", models.PositiveSmallIntegerField(default=5)),
            ],
        ),
    ]
