# Generated by Django 5.0.1 on 2024-03-12 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_aktor_extrainfo_ocena"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extrainfo",
            name="rezyser",
        ),
        migrations.AddField(
            model_name="aktor",
            name="filmy",
            field=models.ManyToManyField(to="main.film"),
        ),
        migrations.AddField(
            model_name="extrainfo",
            name="film",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.film",
            ),
        ),
        migrations.AddField(
            model_name="extrainfo",
            name="punkty_widzow",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ocena",
            name="film",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.film"
            ),
        ),
        migrations.AlterField(
            model_name="extrainfo",
            name="gatunek",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Horror"),
                    (4, "Dramat"),
                    (0, "Inne"),
                    (2, "Komedia"),
                    (3, "Sci-fi"),
                ],
                null=True,
            ),
        ),
    ]
