# Generated by Django 5.0.1 on 2024-03-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_extrainfo_rezyser_aktor_filmy_extrainfo_film_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrainfo",
            name="gatunek",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Inne"),
                    (4, "Dramat"),
                    (2, "Komedia"),
                    (3, "Sci-fi"),
                    (1, "Horror"),
                ],
                null=True,
            ),
        ),
    ]
